const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={view:'garden',filter:'active',cat:'All',query:'',selected:null,edit:null,month:new Date(),selectedDate:new Date().toISOString().slice(0,10),theme:'pink'};
const saved=JSON.parse(localStorage.getItem('panGardenV4')||'null');
let products=saved?.products||SEED_PRODUCTS; let history=saved?.history||[]; let settings=saved?.settings||{seasonal:true,celebrate:true,reminders:true,defaultGoal:30};
function save(){localStorage.setItem('panGardenV4',JSON.stringify({products,history,settings}))}
function pct(p){return Math.min(100,Math.round((p.uses||0)/Math.max(1,p.goal)*100))}
function plant(p){let x=pct(p); if(x>=100)return p.plant==='pink'?'🌺':'🌻'; if(x>=67)return p.plant==='pink'?'🌷':'🌿'; if(x>=34)return '🪴'; if(x>0)return '🌱'; return '🌱'}
function type(p){if(p.category==='Blush')return p.brand==='Glossier'?'tube':'blush';if(p.category==='Lips')return 'lip';if(p.category==='Eyes')return 'eye';if(p.category==='Base')return 'base';return 'tube'}
function productVisual(p,big=false){return `<span class="prod ${type(p)}" style="--shade:${p.shade||'#b98282'};${big?'transform:scale(1.8);margin:35px':''}"></span>`}
function addUse(id){let p=products.find(x=>x.id===id); if(!p)return;p.uses=(p.uses||0)+1;history.push({id,date:new Date().toISOString()});save();render()}
function nav(v){state.view=v;render();scrollTo(0,0)}
function header(title,sub='',right=''){return `<div class="topbar"><div class="titleBlock"><h1>${title}</h1>${sub?`<p>${sub}</p>`:''}</div>${right}</div>`}
function bottom(){return `<nav class="bottomNav"><button class="navBtn ${state.view==='garden'?'on':''}" onclick="nav('garden')"><span>🌱</span>Garden</button><button class="navBtn ${state.view==='collection'?'on':''}" onclick="nav('collection')"><span>♧</span>Collection</button><button class="addFab" onclick="newProduct()">+</button><button class="navBtn ${state.view==='stats'?'on':''}" onclick="nav('stats')"><span>▥</span>Stats</button><button class="navBtn ${state.view==='panned'?'on':''}" onclick="nav('panned')"><span>♡</span>Panned</button></nav>`}
function garden(){let list=products.filter(p=>state.filter==='all'||state.filter==='finished'&&p.uses>=p.goal||state.filter==='active'&&p.active&&p.uses<p.goal);return `<section class="screen">${header('Project Pan','small steps, happy pans ✨',`<button class="iconBtn" onclick="nav('settings')">⚙</button>`)}<div class="gardenHero"><div class="hill"></div><span class="flowerDot" style="left:12px;bottom:28px">🌼</span><span class="flowerDot" style="left:110px;bottom:18px">🌸</span><span class="flowerDot" style="right:100px;bottom:17px">🌷</span><div class="plantScene sceneLeft"><div class="plantPot pink"><i class="stem"></i><i class="leaf l1"></i><i class="leaf l2"></i><span class="blossom">🌸</span><span class="face">•ᴗ•</span></div></div><div class="plantScene sceneRight"><div class="plantPot green"><i class="stem"></i><i class="leaf l1"></i><i class="leaf l2"></i><i class="leaf l3"></i><span class="face">•ᴗ•</span></div></div></div><div class="filters">${['active','all','finished'].map(x=>`<button class="chip ${state.filter===x?'on':''}" onclick="state.filter='${x}';render()">${x[0].toUpperCase()+x.slice(1)}</button>`).join('')}<button class="chip" onclick="nav('calendar')">Calendar</button></div><div class="sectionHead"><h2>Your garden</h2><button onclick="nav('collection')">See all</button></div><div class="productGrid">${list.map(card).join('')||'<div class="empty">Pick products from Collection to grow your garden 🌱</div>'}</div>${bottom()}</section>`}
function card(p){return `<article class="productCard" onclick="detail('${p.id}')"><div class="brand">${p.brand}</div><div class="pname">${p.name}</div><div class="visualRow">${productVisual(p)}<span class="miniPlant">${plant(p)}</span></div><div class="progress"><i style="width:${pct(p)}%"></i></div><div class="useRow"><span>${p.uses}/${p.goal}</span><button class="tinyPlus" onclick="event.stopPropagation();addUse('${p.id}')">+1</button></div></article>`}
function detail(id){state.selected=id;state.view='detail';render();scrollTo(0,0)}
function detailView(){let p=products.find(x=>x.id===state.selected);if(!p)return garden();return `<section class="screen"><div class="topbar"><button class="iconBtn back" onclick="nav('garden')">‹</button><b>${p.brand}</b><button class="iconBtn" onclick="editProduct('${p.id}')">✎</button></div><div class="detailHero">${productVisual(p,true)}<span style="font-size:100px;filter:drop-shadow(0 8px 6px #6d4a3830)">${plant(p)}</span></div><div class="detailCard"><div class="tags"><span class="tag">${p.category}</span><span class="tag">${p.brand}</span><span class="tag">${p.active?'Active Pan':'Reserve'}</span></div><div class="bigCount">${p.uses} / ${p.goal} <small style="font-size:13px;font-weight:500">uses</small></div><div class="progress"><i style="width:${pct(p)}%"></i></div><div class="stageRow"><div class="stage">🌱<small>0</small></div><div class="stage">🪴<small>10</small></div><div class="stage">🌿<small>20</small></div><div class="stage">🌷<small>${p.goal}</small></div><div class="stage">🌺<small>Panned</small></div></div><button class="bigUse" onclick="addUse('${p.id}')">+1 Use</button><div class="notes"><b>Notes</b><br>${p.notes||'No notes yet. Tap Edit to add pairing ideas or shade notes.'}</div></div></section>`}
function collection(){let cats=['All','Lips','Blush','Eyes','Base','Other'];let list=products.filter(p=>(state.cat==='All'||p.category===state.cat)&&(`${p.brand} ${p.name}`.toLowerCase().includes(state.query.toLowerCase())));return `<section class="screen">${header('Collection','${products.length} products')}<div class="searchWrap"><input class="search" placeholder="⌕  Search products, brands…" value="${state.query}" oninput="state.query=this.value;render()"></div><div class="filters">${cats.map(c=>`<button class="chip ${state.cat===c?'on':''}" onclick="state.cat='${c}';render()">${c}</button>`).join('')}</div><div class="collectionList">${list.map(p=>`<div class="collectionRow" onclick="detail('${p.id}')"><div class="thumb">${productVisual(p)}</div><div><div class="rowTitle">${p.brand} · ${p.name}</div><div class="rowMeta">${p.category} · ${p.active?'Active':'Reserve'} · ${p.uses}/${p.goal}</div><div class="progress"><i style="width:${pct(p)}%"></i></div></div><span>›</span></div>`).join('')}</div>${bottom()}</section>`}
function stats(){let total=products.reduce((a,p)=>a+p.uses,0),finished=products.filter(p=>p.uses>=p.goal).length,active=products.filter(p=>p.active&&p.uses<p.goal).length,days=new Set(history.map(h=>h.date.slice(0,10))).size;let cats=['Lips','Blush','Eyes','Base','Other'], vals=cats.map(c=>[c,products.filter(p=>p.category===c).reduce((a,p)=>a+p.uses,0)]),max=Math.max(1,...vals.map(x=>x[1]));return `<section class="screen">${header('Stats')}<div class="filters"><button class="chip on">This Month</button><button class="chip">All Time</button><button class="chip">By Category</button></div><div class="statsGrid"><div class="statCard"><strong>🌿 ${total}</strong><span>Total Uses</span></div><div class="statCard"><strong>🌸 ${active}</strong><span>Products In Progress</span></div><div class="statCard"><strong>🌱 ${finished}</strong><span>Products Finished</span></div><div class="statCard"><strong>⭐ ${days}</strong><span>Days Tracked</span></div></div><div class="sectionHead"><h2>Usage by Category</h2></div><div class="barList">${vals.map(([c,v])=>`<div class="barRow"><span>${c}</span><div class="barTrack"><i style="width:${v/max*100}%"></i></div><b>${v}</b></div>`).join('')}</div>${bottom()}</section>`}
function panned(){let done=products.filter(p=>p.uses>=p.goal);return `<section class="screen"><div class="topbar"><button class="iconBtn back" onclick="nav('garden')">‹</button><div class="titleBlock"><h1>Panned Garden</h1></div><span></span></div><div class="pannedScene"><span class="flowerDot" style="left:25px;top:40px">🌸</span><span class="flowerDot" style="right:20px;top:90px">🌼</span><div class="pannedPlants">${done.length?done.map(p=>`<div class="trophy"><div class="bigPlant">${p.plant==='pink'?'🌺':'🌿'}</div><div class="plaque">${p.brand}<br><b>${p.name}</b><br>PANNED</div></div>`).join(''):`<div class="empty" style="grid-column:1/-1">Your finished products will grow into this garden 🌱</div>`}</div><div class="celebrate">Look at you go! 🌸<br>Every pan is a win.</div></div>${bottom()}</section>`}
function calendar(){let d=state.month,y=d.getFullYear(),m=d.getMonth(),first=new Date(y,m,1).getDay(),last=new Date(y,m+1,0).getDate(),cells=''.padStart(first,' ').split('').map(()=>'<span></span>').join('');for(let day=1;day<=last;day++){let key=`${y}-${String(m+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`,has=history.some(h=>h.date.startsWith(key));cells+=`<button class="day ${has?'has':''} ${state.selectedDate===key?'sel':''}" onclick="state.selectedDate='${key}';render()">${day}</button>`}let logs=history.filter(h=>h.date.startsWith(state.selectedDate));return `<section class="screen"><div class="topbar"><button class="iconBtn back" onclick="nav('garden')">‹</button><b>${d.toLocaleString('default',{month:'long'})} ${y}</b><button class="iconBtn" onclick="state.month=new Date(y,m+1,1);render()">›</button></div><div class="calendar"><div class="calHead"><button class="iconBtn" onclick="state.month=new Date(y,m-1,1);render()">‹</button><span>Usage Calendar</span><span></span></div><div class="week">${['S','M','T','W','T','F','S'].map(x=>`<span>${x}</span>`).join('')}</div><div class="days">${cells}</div></div><div class="dayLog"><b>${state.selectedDate}</b>${logs.length?logs.map(h=>{let p=products.find(x=>x.id===h.id);return p?`<div class="logRow">${productVisual(p)}<span>${p.name}</span><b style="margin-left:auto">+1 use</b></div>`:''}).join(''):'<div class="empty">No uses logged this day.</div>'}</div></section>`}
function newProduct(){state.edit={id:'custom-'+Date.now(),brand:'',name:'',category:'Lips',shade:'#b36f78',goal:settings.defaultGoal,uses:0,active:true,plant:'pink',notes:''};state.view='edit';render()}
function editProduct(id){state.edit={...products.find(x=>x.id===id)};state.view='edit';render()}
function formView(){let p=state.edit;return `<section class="screen"><div class="topbar"><button class="iconBtn back" onclick="${products.some(x=>x.id===p.id)?`detail('${p.id}')`:`nav('collection')`}">‹</button><b>${products.some(x=>x.id===p.id)?'Edit Product':'Add Product'}</b><button class="saveBtn" onclick="saveForm()">Save</button></div><div class="form"><div class="previewBox">${productVisual(p,true)}<span style="font-size:70px">${p.plant==='pink'?'🌸':'🌿'}</span></div>${field('Name',`<input id="fName" value="${esc(p.name)}">`)}${field('Brand',`<input id="fBrand" value="${esc(p.brand)}">`)}${field('Category',`<select id="fCat">${['Lips','Blush','Eyes','Base','Other'].map(x=>`<option ${p.category===x?'selected':''}>${x}</option>`).join('')}</select>`)}${field('Goal (uses)',`<input id="fGoal" type="number" value="${p.goal}">`)}${field('Active project pan',`<select id="fActive"><option value="true" ${p.active?'selected':''}>Active</option><option value="false" ${!p.active?'selected':''}>Reserve</option></select>`)}<div class="field"><label>Choose a Plant</label><div class="plantChoices"><button class="plantChoice ${p.plant==='pink'?'on':''}" onclick="state.edit.plant='pink';render()">🌸</button><button class="plantChoice ${p.plant==='green'?'on':''}" onclick="state.edit.plant='green';render()">🌿</button></div></div>${field('Notes',`<textarea id="fNotes">${esc(p.notes||'')}</textarea>`)}</div></section>`}
function field(l,c){return `<div class="field"><label>${l}</label>${c}</div>`} function esc(s=''){return String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;')}
function saveForm(){let p={...state.edit,name:$('#fName').value,brand:$('#fBrand').value,category:$('#fCat').value,goal:+$('#fGoal').value||30,active:$('#fActive').value==='true',notes:$('#fNotes').value};let i=products.findIndex(x=>x.id===p.id);if(i>=0)products[i]=p;else products.unshift(p);save();detail(p.id)}
function settingsView(){return `<section class="screen"><div class="topbar"><button class="iconBtn back" onclick="nav('garden')">‹</button><b>Appearance</b><span></span></div><div class="themeGrid">${[['pink','🌸','Pink & Green','#efd0cf'],['sage','🌿','Sage','#dbe6d8'],['warm','🌼','Warm','#ecd6aa'],['slate','🪻','Slate','#cfd8df']].map(([id,ico,n,bg])=>`<button class="theme ${state.theme===id?'on':''}" onclick="setTheme('${id}')"><div class="themePlant" style="background:${bg}">${ico}</div>${n}</button>`).join('')}</div><div class="settings"><div class="setting"><span>Use Seasonal Icons</span><button class="toggle ${settings.seasonal?'on':''}" onclick="settings.seasonal=!settings.seasonal;save();render()"><i></i></button></div><div class="setting"><span>Default use goal</span><b>${settings.defaultGoal}</b></div><div class="setting"><span>Show celebrations</span><button class="toggle ${settings.celebrate?'on':''}" onclick="settings.celebrate=!settings.celebrate;save();render()"><i></i></button></div><div class="setting"><span>Gentle reminders</span><button class="toggle ${settings.reminders?'on':''}" onclick="settings.reminders=!settings.reminders;save();render()"><i></i></button></div></div><div class="sectionHead"><h2>Data</h2></div><div class="settings"><div class="setting" onclick="exportData()"><span>Export Data (JSON)</span><b>⇩</b></div><label class="setting"><span>Import Data</span><b>⇧</b><input type="file" accept="application/json" style="display:none" onchange="importData(this)"></label></div><p class="codeNote">Your collection and use history are stored locally in this browser. Export a backup occasionally.</p></section>`}
function setTheme(t){state.theme=t;let root=document.documentElement;if(t==='sage'){root.style.setProperty('--pink','#91a68d');root.style.setProperty('--bg','#eef2e9')}else if(t==='warm'){root.style.setProperty('--pink','#d69b69');root.style.setProperty('--bg','#f8efe0')}else if(t==='slate'){root.style.setProperty('--pink','#8297a5');root.style.setProperty('--bg','#edf0f2')}else{root.style.setProperty('--pink','#d98791');root.style.setProperty('--bg','#f8eee7')}render()}
function exportData(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({products,history,settings},null,2)],{type:'application/json'}));a.download='pan-garden-backup.json';a.click()}
function importData(inp){let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);products=d.products||products;history=d.history||history;settings=d.settings||settings;save();render()}catch(e){alert('That backup file could not be read.')}};r.readAsText(inp.files[0])}
function render(){let html=state.view==='garden'?garden():state.view==='collection'?collection():state.view==='detail'?detailView():state.view==='edit'?formView():state.view==='stats'?stats():state.view==='panned'?panned():state.view==='calendar'?calendar():settingsView();$('#app').innerHTML=`<main class="shell">${html}</main>`}
render(); if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
